#!/usr/bin/env python

import rospy
import sys

from python_qt_binding.QtGui import *
from python_qt_binding.QtCore import *
from python_qt_binding.QtWidgets import *

from qt_smach_viewer.viewer import SmachViewerFrame


def main():    
    a = QApplication(sys.argv)
    import signal
    window = QMainWindow()
    frame = SmachViewerFrame(window)
    window.setCentralWidget(frame)
    window.show()
    signal.signal(signal.SIGINT, signal.SIG_DFL)
    sys.exit(a.exec_())

if __name__ == '__main__':
    rospy.init_node('smach_viewer',anonymous=False, disable_signals=False,log_level=rospy.INFO)
    
    main()

    
#End of file
